### ISSUE TITLE
Работа с Видео

### ISSUE THREAD

**Issue by npopeka** [galtspace/galtproject-docs#127]
Видео № 3, надо добавить:
1. Обмен происходит автоматически при помощей умного контракта. Проект берет комиссию, от каждой транзакции. Если пользователь отправляет эфиры, то комиссия берется в эфирах, если GALT, то в GALT. Эфиры и токены GALT за вычетом комиссии полностью попадают на умных контракт и используются для дальнейших обменных операций. Создатели проекта не имеют доступа к этим средствам.
2. Курс обмена определяется автоматически, исходя из того, сколько Эфиров находится на умном контракте GaltDex и сколько токенов  GALT находится у пользователей.

Видео 4:
1. Переделать с учетом нового интерфейса.
2. Сказать, что “сдача” от перечисленных на внутренний кошелек средств будет возвращена автоматически.
3. Сказать, что временный кошелек создается каждый раз новый.
4. Сказать, что приложение просит дать право на выполнение операции с заявкой внутреннему кошельку.
5. Сказать, что приложение блокируется пока право не будет отозвано от внутреннего кошелька на основной адрес пользователя.
6. Дать определение Валидатору - нотариус, юрист или геодезист, которые проверяют заявку.

Видео 6
1. Мало комментариев.  Нужно говорить, что заходим в таком то меню и нажимаем то - то.
2. В меню выбора геохешей нужно сказать: Каждый геохеш добавляется вручную, Вы можете нажать на карту и Геохей максимальной точности будет скопирован в буфер обмена. Вам останется только вставить его в поле для ввода и убрать лишние символы. Обратите внимание, что введенный геохеш подсвечивается на карте. Вы можете добавить новый геохеш только, если он соседствует с геохешем, который был добавлен ранее.

**Comment by IgorFrolov** [comment]
Видео 3 - done

**Comment by IgorFrolov** [comment]
Видео 6 - done

**Comment by IgorFrolov** [comment]
Видео 4 - fail
https://www.youtube.com/watch?v=G4V0tnnDUVk
