### ISSUE TITLE
Штраф репутации при факте сдачи участка в аренду

### ISSUE THREAD

**Issue by Jonybang** [galtspace/galtproject-docs#77]
Каким образом произойдет штраф репутации если репутация SPACE токена уже распределена между арендаторами?

Вариант решения:
- Невозможность совершить штраф, пока не будет revoke-нута вся репутация space токена

Возможная проблема при таком решении:
- Владелец участка постоянно передает в аренду часть репутации участка, не давая тем самым оштрафовать свой участок

**Comment by chebykin** [comment]
Мне вот кажется, что надо простимулировать владельца Space токена самостоятельно выплачивать штраф и самостоятельно определять у каких участников доли эта репутация будет списываться. Вопрос - что это за мотивации могут быть?

**Comment by chebykin** [comment]
obsolete
